---
- hosts: webserver
  become: true
  tasks:
  - name: installing java 
    apt: package=openjdk-11-jdk state=latest

  - name: Download Tomcat
    get_url: url=https://downloads.apache.org/tomcat/tomcat-10/v10.0.0-M9/bin/apache-tomcat-10.0.0-M9.tar.gz dest=/home/ubuntu

  - name: Extract archive
    unarchive: src=/home/ubuntu/apache-tomcat-10.0.0-M9.tar.gz dest=/home/ubuntu remote_src=yes

  - name: copy DevOpsRocks.war
    src: /var/lib/jenkins/workspace/war-deploy-tomcat/target/DevOpsRocks.war dest=/home/ubuntu/
  
  - name: copying the war file to server
    shell: cp /home/ubuntu/DevOpsRocks.war /home/ubuntu/apache-tomcat-10.0.0-M9/webapps/

  - name: start apache-tomcat-10.0.0-M9
    shell: /home/ubuntu/apache-tomcat-10.0.0-M9/bin/startup.sh

